application-name: ODP
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.kingleadsw.ysm.po
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-delete-value: 2
    logic-not-delete-value: 1
    capital-mode: false
    db-column-underline: true
    id-type: 0
    metaObjectHandler: com.kingleadsw.ysm.datascource.FillerObjectHandler
    refresh-mapper: true
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.kingleadsw.ysm.po
redis:
#  hostName: 120.79.18.131
  hostName: 127.0.0.1
  maxIdle: 300
  maxTotal: 1000
  maxWaitMillis: 1000
  minEvictableIdleTimeMillis: 300000
  numTestsPerEvictionRun: 1024
#  password: 'qpc_redis'
  database: 1
  password: '123456'
  testOnBorrow: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 30000
server:
  port: 12004
  session-timeout: 1800
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    log-abandoned: true
    max-active: 15
    max-idle: 10
    max-lifetime: 60000
    password: kld@2016!_0rd
    remove-abandoned: true
    remove-abandoned-timeout: 60
    sqlScriptEncoding: UTF-8
    url: jdbc:mysql://120.79.18.131:3306/hami_test?useUnicode=true&characterEncoding=utf8
    username: kingleadsw
  profiles: dev
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
swagger:
  is:
    enable: true
  package: com.kingleadsw
wechat:
  appid: wxcc1f50b04e123e2f
  secret: f15f1b14e5012604070a09ad36f7528d

beyondh:
  domain: pms
  key: INTERFACE
  app_key: 86O4K6YG5U2N6TDR52TVSE2R6AW5
  hotel_id: 288733476028418
  url: http://pms.beyondh.com:7897

sysconfig:
  constants:
    upload-path: D:\\home\\projects\\kingleadsw\\
    qiniu:
      qiniu_access_key: WSuHkUs_mu5V4exwlYNyL9FuaVgSTz42-FREL8gw
      qiniu_secret_key: QkNz8wwuveSGFTFHybSf6huBrp6Qps-4Cr3f20WC
      qiniu_cloud_key: hami-education
      qiniu_link: http://resqn.17hami.com/
      encrypt_notify: www.17hami.com
      media_queue: hami-media
