application-name: MTP
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.kingleadsw.ysm.po
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-delete-value: 2
    logic-not-delete-value: 1
    capital-mode: false
    db-column-underline: true
    id-type: 0
    metaObjectHandler: com.kingleadsw.ysm.datascource.FillerObjectHandler
    refresh-mapper: true
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.kingleadsw.ysm.po
redis:
#  hostName: 120.79.18.131
  hostName: 127.0.0.1
  maxIdle: 300
  maxTotal: 1000
  maxWaitMillis: 1000
  minEvictableIdleTimeMillis: 300000
  numTestsPerEvictionRun: 1024
#  password: 'qpc_redis'
  password: '123456'
  database: 1
  #password: '123456'
  testOnBorrow: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 30000
server:
  port: 8085
  session-timeout: 1800
  context-path: /hc-mtp-api
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    log-abandoned: true
    max-active: 15
    max-idle: 10
    max-lifetime: 60000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    sqlScriptEncoding: UTF-8
    url: jdbc:mysql://120.79.18.131:3306/sports_media?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: kingleadsw
    password: kld@2016!_0rd
#    url: jdbc:mysql://172.16.0.90:3306/sports_media?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: system
#    password: 123456
  profiles: dev
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
swagger:
  is:
    enable: true
  package: com.kingleadsw
sysconfig:
  constants:
    upload-path: /home/projects/kingleadsw/huachensports
    qiniu:
      #七牛账号
      qiniu_access_key: bJYZ8gFHNwuB6ssqfN-NlGhpus-9lYUoYlWhkyJH
      qiniu_secret_key: dC6ihk2dRpkUSkhKONWaJJqWl5VS5lFFul7P2tpN
      qiniu_cloud_key: zhuawawa
      qiniu_link: http://res.sutuizs.com/
beyondh:
  domain: pms
  key: INTERFACE
  app_key: 86O4K6YG5U2N6TDR52TVSE2R6AW5
  hotel_id: 288733476028418
  url: http://pms.beyondh.com:7897

wechat:
  pay:
    appid: wx1cd2b5d81c1d359a
    secret: 4kkx4eu4dqvzmnetpexialqcvkxly15d
    payurl: https://api.mch.weixin.qq.com/pay/unifiedorder
    notify_url: http://ysmdoc.sutuizs.com/pay/wxnotify
  appid: wx1cd2b5d81c1d359a
  secret: 1e965c0369a18b415d1e77202224c319

short:
  url: http://smssh1.253.com/msg/send/json
  account: N234202_N4203465
  password: hq9M5eJftB1c34